---
version: '3.8'

x-base-logging: &base-logging
  logging:
    driver: "json-file"
    options:
      max-size: "20m"
      max-file: "10"


services:

  lotus:
    <<: *base-logging
    image: docker.services.kindstudios.gr/permanentum-lotus:${LOTUS_VERSION}
    build:
      context: ./lotus
      args:
        VERSION: "${LOTUS_VERSION}"
        NET: $FILECOIN_NETWORK
    volumes:
    - type: bind
      source: $LOTUS_STORAGE
      target: /lotus
    - type: bind
      source: $LOTUS_KEYSTORE
      target: /lotus/keystore
    environment:
      LOTUS_PATH: /lotus
      BOOTSTRAP: "${LOTUS_BOOTSTRAP}"
    #restart: on-failure
    ports:
    - "127.0.0.1:17010:1234"
    profiles: [ "filecoin" ]

  ipfs:
    <<: *base-logging
    restart: on-failure
    image: ipfs/kubo:v0.20.0
    profiles: [ "ipfs" ]
    environment:
      IPFS_PROFILE: server
      IPFS_PATH: /ipfsdata
      WEB_UI_IP: ${TUN0}
      IPFS_LOGGING: info
    volumes:
      - ${IPFS_STORAGE}:/ipfsdata
      - ./ipfs:/container-init.d
    ports:
      - "${PORT_RANGE_PREFIX}20:4001/tcp"         # ipfs gossip
      - "${PORT_RANGE_PREFIX}20:4001/udp"         # ipfs gossip
      - "127.0.0.1:${PORT_RANGE_PREFIX}21:8080" # gateway local access (nginx)
      - "${TUN0}:${PORT_RANGE_PREFIX}21:8080"   # gateway vpn access (dev)
      - "${TUN0}:${PORT_RANGE_PREFIX}22:8081" # websocket-listener
      - "${TUN0}:${PORT_RANGE_PREFIX}23:5001" # api server (don't expose externally)

volumes:
  nix-storage:
  cardano-socket:

